{% set version = "0.4.6" %}

package:
  name: cbsyst
  version: {{ version }}

source:
  url: https://github.com/oscarbranson/cbsyst/archive/{{ version }}.tar.gz
  sha256: 972e15a030bd556fbc212e8e845c498654375a3743de383885cef11bd158617f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - numpy >=1.13
    - scipy >=0.18
    - pandas >=0.19
    - uncertainties >=3.0
    - tqdm >=4.14
    - kgen >=0.0.2

test:
  imports:
    - cbsyst
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/oscarbranson/cbsyst
  license: MIT
  license_file: LICENCE.txt
  summary: Tools for calculating ocean C and B chemistry

extra:
  recipe-maintainers:
    - ocefpaf
