{% set version = "0.4.9" %}

package:
  name: cbsyst
  version: {{ version }}

source:
  url: https://github.com/oscarbranson/cbsyst/archive/{{ version }}.tar.gz
  sha256: 9219ad80d5118cdcd2ad8276c8eda98424e53647cbada8ce19693c472d4da652

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - numpy >=1.13
    - scipy >=0.18
    - pandas >=0.19
    - uncertainties >=3.0
    - tqdm >=4.14
    - kgen >=0.2.0

test:
  imports:
    - cbsyst
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/oscarbranson/cbsyst
  license: MIT
  license_file: LICENCE.txt
  summary: Tools for calculating ocean C and B chemistry

extra:
  recipe-maintainers:
    - ocefpaf
