{% set version = "0.3.7" %}

package:
  name: cbsyst
  version: {{ version }}

source:
  url: https://github.com/oscarbranson/cbsyst/archive/{{ version }}.tar.gz
  sha256: 829a47c52dce3fc390dd9d35a9de3c785278e84a1cf895a034b7951e300819d4

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv

requirements:
  host:
    - python >=3
    - pip
  run:
    - python >=3
    - numpy
    - scipy
    - uncertainties
    - tqdm
    - pandas

test:
  imports:
    - cbsyst

about:
  home: https://github.com/oscarbranson/
  license: MIT
  license_file: LICENCE.txt
  summary: Tools for calculating ocean C and B chemistry

extra:
  recipe-maintainers:
    - ocefpaf
