{% set version = "0.3.6" %}

package:
  name: cbsyst
  version: {{ version }}

source:
  url: https://github.com/oscarbranson/cbsyst/archive/{{ version }}.tar.gz
  sha256: 947b7ea73875520f400e3912f82e98659fc1f2339d6f377d4e127e45f751d2f3

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv"

requirements:
  host:
    - python >=3
    - pip
  run:
    - python >=3
    - numpy
    - scipy
    - uncertainties
    - tqdm
    - pandas

test:
  imports:
    - cbsyst

about:
  home: https://github.com/oscarbranson/
  license: MIT
  license_file: LICENCE.txt
  summary: 'Tools for calculating ocean C and B chemistry'

extra:
  recipe-maintainers:
    - ocefpaf
