{% set version = "0.4.2" %}

package:
  name: cbsyst
  version: {{ version }}

source:
  url: https://github.com/oscarbranson/cbsyst/archive/v{{ version }}.tar.gz
  sha256: 97c2c012f369bb8c90e2779e023c46ca8d6eab7bde424f531d9adf34553b64d8

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - numpy >=1.13
    - scipy >=0.18
    - pandas >=0.19
    - uncertainties >=3.0
    - tqdm >=4.14
    - kgen >=0.0.2

test:
  imports:
    - cbsyst
  # pymyami 2.0a4 declares sklearn instead of scikit-learn.
  # commands:
  #   - pip check
  # requires:
  #   - pip

about:
  home: https://github.com/oscarbranson/cbsyst
  license: MIT
  license_file: LICENCE.txt
  summary: Tools for calculating ocean C and B chemistry

extra:
  recipe-maintainers:
    - ocefpaf
