{% set version = "0.4.8" %}

package:
  name: cbsyst
  version: {{ version }}

source:
  url: https://github.com/oscarbranson/cbsyst/archive/{{ version }}.tar.gz
  sha256: 5fa2dfa663a0dc6782506b9f718d44f47b905de82ddf07993dd610acde16e5b9

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - numpy >=1.13
    - scipy >=0.18
    - pandas >=0.19
    - uncertainties >=3.0
    - tqdm >=4.14
    - kgen >=0.2.0

test:
  imports:
    - cbsyst
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/oscarbranson/cbsyst
  license: MIT
  license_file: LICENCE.txt
  summary: Tools for calculating ocean C and B chemistry

extra:
  recipe-maintainers:
    - ocefpaf
