travis:
  secure:
    BINSTAR_TOKEN: yozdHHJN47NCQw2TjaYvrjAOPDA0Wm1RWXkmGeZArpOyxtmB141/EfIiktJOHH5dArgdQk6SScR0CFciBGhUN/sp57V6+rxYmjseJJPbZbru5F3dOQvqM7Wpft8G+E5Y6PecKv7jr+GA2ukh/9XgrbRCqrhrTjiGT5InEgll+X/xVGUJWaOV0EcMFuz7agxol4adIjweXSNgXgWhg9c0bcmIjE+8rTY3NpAs4OZ7rBFecBGZawlfrgXZ6xNPAHTUdma8LIsfEv4H8pJGmDTHpdIVzJpbbAcgIFJPVhbpVK73bqVkRr6UuSSQxKNnKU5yuGCpIwZT82w1z6QKbP1NA5tIgNGTiprV7qMChLHdYumbEP5PaRwWAzx1Fg5b9pQv52AAuS/Zd8Y3Qx+LarIIz4bIPLc5QH8P2SAjVw54Iwfpbv2CkLINivcD4hNhQNY+92JHd8vCBmKIYYpPbyfZtLOyAn4QPUG/Nq9r4VU9U/VYn8eIRkLIvwy/c/vM9tTe1t9wBtg8hGaT27xjtfkQunfm58lord0gVXzKkp/erhgBXGFExMucj239w4meVkvknjh1RWaNAu/aERejBeHJ7zlPXUGt8Sz5xuB/owsRA6GrEHrMLwpSwM79GayJNeteUBG6Q7J2/jNqhatWvT221e4fd/6vMp0QxLYKSQ3Z6/k=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
