appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: HJewlcSqPoxcS1RixwNNC1FZB876fWcbPU/DP3oTlN2l+AFpOTgEFhYzMy1uvclwqtkqPhi0651N9qLinKfb94bv8HYrrl+bY5coCnFnfDkvReOm8aBYz24pTq05pYSF3JG7rnlQIwcQNnvM0MHf6Ldp9hvFJX5HVNjEoZrP0MTclWiCzYgbNdB16OwTPDMwfjkQldOt84XCyReLpo1B65PVfaLRauiI5gv7gvV+EYv2D4vQ3kdTDZrwYD/xNYYMEPhzi9HPnQ5naK3SXBwWTrJhD+Zl3e4mzT/gVBK9HZO3Djn6AOyybQYmLa2sPmmekrtScb8ixLEvVkM0Z0XbfB4N7q2O2o1tbb2RjjgmS6P6M0DPxSuPkxZyzEipM/PefSim1GwerffTKhoq/+oagZNJBmx3X3uF2MlqkO1epUee7qTFhQQ6pknUm1TgN2CQxCOmydm+ndI7Wa8LQrh7F9D7XK3ewx13dcftnaoEjnwBA+73ofVCfPznacnmdNEImvZo9QtXA5qDa5zhHaK2o1hityC01TEDHbIBbACJpEVQRRscPMS0tk2DYugGdUiSD4L5IpNS7JFITWTv7IsPTW/TQFA9Zu2xizqPXUg2gMGuAGiddeQCUgx0iWemfilDSFqrMgxaswrtIqHw2BlDcTERBnTjfFk157/vvt2q0kI=}
